dist: trusty
sudo: false

language: cpp

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-5

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      install:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      install:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      install:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      install:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

after_success:
  - ./app

script:
  - g++ -v
  - make all
